# Playbbook to commit candidate config on firewall
# REQUIREMENTS
# pip install pan-python
# pip install pandevice
# pip install xmltodict
# ansible-galaxy install paloaltonetworks.paloaltonetworks

---
- name: Apply Candidate config to PAN Firewalls
  hosts: Palo
  connection: local
  collections:
    - paloaltonetworks.panos

  tasks:
  - name: commit candidate config on firewall
    panos_commit_firewall:
      provider: '{{ provider }}'
...