# Playbbook to apply ACL to Palo FW

# REQUIREMENTS
# pip install pan-python
# pip install pandevice
# pip install xmltodict
# ansible-galaxy install paloaltonetworks.paloaltonetworks
# https://www.bountysource.com/issues/59738537-certificate-verify-failed
# et verify to disable in the virtual environment

---
- name: Apply ACLs to PAN Firewalls
  hosts: panos
  connection: local
  gather_facts: False
  vars:
    erase: false
  vars_files:
    - ./vars/default_vars.yml
    - ./credentials/pan_credentials.yml
  roles:
    - role: paloaltonetworks.paloaltonetworks

  tasks:

    - name: commit candidate config on firewall
      panos_commit:
        ip_address: "{{ ansible_host }}"
        username: "{{ PAN_USERNAME }}"
        password: "{{ PAN_PASSWORD }}"

...