## PLAYBOOK
# Playbook to build baseline configuration on the firewall
## DESCRIPTION
# Example playbook that will connect to the firewall using credentials provided saved in host var file 
## REQUIREMENTS
# pip install ansible
# ansible-galaxy install PaloAltoNetworks.paloaltonetworks
## EXECUTE
# ansible-playbook palo-base-build.yaml
---
- name: Build baseline configuration on the firewall
  hosts: PA-FW-01
  connection: local
  gather_facts: False

  collections:
    - paloaltonetworks.panos

  tasks:
  - name: Add an address object to the firewall
    panos_object:
      provider: '{{ provider }}'
      addressobject: 'host-1.2.3.4'
      address: '1.2.3.4'
      address_type: 'ip-netmask'
      description: 'This is a test address object'
      operation: 'add'

  - name: Add another address object to the firewall
    panos_object:
      provider: '{{ provider }}'
      addressobject: 'range-192.168.100.100-200'
      address: '192.168.100.100-192.168.100.200'
      address_type: 'ip-range'
      description: 'This is a another test address object'
      operation: 'add'

  - name: Add yet another address object to the firewall
    panos_object:
      provider: '{{ provider }}'
      addressobject: 'net-10.0.0.0-8'
      address: '10.0.0.0/8'
      address_type: 'ip-netmask'
      description: 'This is a another test address object'
      operation: 'add'

  - name: Add an address group to the firewall
    panos_object:
      provider: '{{ provider }}'
      addressgroup: 'test-address-group'
      static_value: ['host-1.2.3.4', 'range-192.168.100.100-200']
      description: 'This is a test addressgroup'
      operation: 'add'

  - name: Add a service to the firewall
    panos_object:
      provider: '{{ provider }}'
      serviceobject: 'service-xyz'
      protocol: 'tcp'
      destination_port: '8889'
      description: 'This is a test service object'
      operation: 'add'

  - name: Add another service to the firewall
    panos_object:
      provider: '{{ provider }}'
      serviceobject: 'service-abc'
      protocol: 'tcp'
      destination_port: '5000,5001,6000-7000'
      description: 'This is a test service object'
      operation: 'add'

  - name: Add a service group to the firewall
    panos_object:
      provider: '{{ provider }}'
      servicegroup: 'test-service-group'
      services: ['service-abc', 'service-xyz']
      description: 'This is a test servicegroup'
      operation: 'add'

  - name: Add a tag to the firewall
    panos_object:
      provider: '{{ provider }}'
      tag_name: 'Test'
      color: 'orange'
      description: 'This is test tag'
      operation: 'add'

  - name: Add test rule 1 to the firewall
    panos_security_rule:
      provider: '{{ provider }}'
      operation: 'add'
      rule_name: 'Ansible test 1'
      description: 'An Ansible test rule'
      source_zone: ['internal']
      destination_zone: ['external']
      source_ip: ['host-1.2.3.4']
      source_user: ['any']
      destination_ip: ['any']
      category: ['any']
      application: ['any']
      service: ['service-xyz']
      hip_profiles: ['any']
      action: 'allow'

  - name: Add test rule 2 to the firewall
    panos_security_rule:
      provider: '{{ provider }}'
      operation: 'add'
      rule_name: 'Ansible test 2'
      description: 'Another Ansible test rule'
      source_zone: ['internal']
      source_ip: ['range-192.168.100.100-200']
      source_user: ['any']
      hip_profiles: ['any']
      destination_zone: ['external']
      destination_ip: ['any']
      category: ['any']
      application: ['any']
      service: ['service-abc']
      action: 'allow'
      group_profile: 'default'

  - name: Add test rule 3 to the firewall
    panos_security_rule:
      provider: '{{ provider }}'
      operation: 'add'
      rule_name: 'Ansible test 3'
      description: 'Yet another Ansible test rule'
      source_zone: ['internal']
      source_ip: ['net-10.0.0.0-8']
      source_user: ['any']
      hip_profiles: ['any']
      destination_zone: ['external']
      destination_ip: ['any']
      category: ['any']
      application: ['any']
      service: ['test-service-group']
      action: 'allow'
      commit: true
...
