## PLAYBOOK
# Playbook to configure BGP Peer Group
## DESCRIPTION
# Playbook that will connect to the firewall using credentials provided saved in host var file 
# add vr_name to host var file
## REQUIREMENTS
# pip install ansible
# ansible-galaxy install PaloAltoNetworks.paloaltonetworks
## EXECUTE
# ansible-playbook palo-bgp-peer-group.yaml
---
- name: Configure BGP Peer Group
  hosts: PA-VM-02
  connection: local
  gather_facts: False

  collections:
    - paloaltonetworks.panos

  tasks:
    - name: Configure BGP Peer Group
      panos_bgp_peer_group:
        provider: '{{ provider }}'
        state: present
        name: peer-group-1
        vr_name: '{{ vr_name }}'
        enable: false
        commit: true

    - name: Update BGP Peer Group
      panos_bgp_peer_group:
        provider: '{{ provider }}'
        state: present
        name: peer-group-1
        vr_name: '{{ vr_name }}'
        enable: true
        aggregated_confed_as_path: true
        export_nexthop: use-self
        import_nexthop: original
        remove_private_as: false
        soft_reset_with_stored_info: false
        type: ebgp
        commit: true

    - name: Remove BGP Peer Group
      panos_bgp_peer_group:
        provider: '{{ provider }}'
        state: absent
        name: peer-group-1
        vr_name: '{{ vr_name }}'
        commit: true
...
