## DESCRIPTION
# Playbook that will connect to the firewall using credentials provided saved in either host.yaml or vars.yaml files and create a VLAN.
## REQUIREMENTS
# pip install ansible
# ansible-galaxy install PaloAltoNetworks.paloaltonetworks
## EXECUTE
# ansible-playbook palo-create-vlan.yaml

---
- name: Create a VLAN on the FW
  hosts: PA-VM-02
  gather_facts: false
  connection: local
  collections:
    - paloaltonetworks.panos.panos_vlan

  tasks:
    - name: Create VLAN 2
      panos_vlan:
        provider: '{{ provider }}'
        name: "test"
        virtual_interface: 'vlan.2'
...