## DESCRIPTION
# Playbook that will connect to the firewall using credentials provided saved in either host.yaml or vars.yaml files and create service object and dynamic NAT.
## REQUIREMENTS
# pip install ansible
# ansible-galaxy install PaloAltoNetworks.paloaltonetworks
## EXECUTE
# ansible-playbook palo-create-serviceobject-NAT.yaml

---
- name: Add New Security rule
  hosts: PA-VM-02
  connection: local
  gather_facts: False

  collections:
    - paloaltonetworks.panos
  
  tasks:
    - name: Add the service object to the firewall first
      panos_service_object:
        provider: '{{ provider }}'
        name: 'service-tcp-221'
        protocol: 'tcp'
        destination_port: '221'
        description: 'SSH on port 221'
        commit: False

    - name: Create dynamic NAT rule on the firewall
      panos_nat_rule:
        provider: '{{ provider }}'
        rule_name: "Web SSH"
        source_zone: ["external"]
        destination_zone: "external"
        source_ip: ["any"]
        destination_ip: ["10.0.0.100"]
        service: "service-tcp-221"
        snat_type: "dynamic-ip-and-port"
        snat_interface: "ethernet1/4"
        dnat_address: "10.0.1.101"
        dnat_port: "22"
        commit: False
...