## PLAYBOOK
# Playbook to create a tunnel interface on the Firewall
## DESCRIPTION
# Example playbook that will connect to the firewall using credentials provided saved in host var file 
## REQUIREMENTS
# pip install ansible
# ansible-galaxy install PaloAltoNetworks.paloaltonetworks
## EXECUTE
# ansible-playbook palo-add-tunnel-interface.yaml
---
- name: Create tunnel interfaces on the Firewall
  hosts: PA-VM-02
  connection: local
  gather_facts: False

  collections:
    - paloaltonetworks.panos

  tasks:
  - name: create tunnel.3
    panos_tunnel:
      provider: '{{ provider }}'
      if_name: "tunnel.3"
      ip: ["10.1.1.1/32"]
      comment: "tunnel interface"

  - name: commit candidate config on firewall
    panos_commit:
      provider: '{{ provider }}'
...
