## PLAYBOOK
# Playbook to create a new administrator
## DESCRIPTION
# Example playbook that will connect to the firewall using credentials provided saved in either host.yaml or vars.yaml files
## REQUIREMENTS
# pip install ansible
# ansible-galaxy install PaloAltoNetworks.paloaltonetworks
## EXECUTE SCRIPT
# ansible-playbook palo-add-admin.yaml
---
- name: Create new Admin user
  hosts: PA-VM-PRI
  gather_facts: false
  connection: local

  collections:
    - paloaltonetworks.panos  
  
  tasks:
    - name: Add a new administrator
      panos_administrator:
        provider: '{{ provider }}'
        admin_username: 'test1'
        admin_password: 'secret123@'
        superuser: true
        commit: true
...