## PLAYBOOK
# Playbook to create a IPSEC VPN and Tunnel on the Firewall
## DESCRIPTION
# Example playbook that will connect to the firewall using credentials provided saved in host var file 
## REQUIREMENTS
# pip install ansible
# ansible-galaxy install PaloAltoNetworks.paloaltonetworks
## EXECUTE
# ansible-playbook palo-add-ipsecvpn.yaml
---
- name: Create a VPN IPSec profile and tunnel on the Firewall
  hosts: PA-VM-PRI
  connection: local
  gather_facts: False

  collections:
    - paloaltonetworks.panos

  tasks:
  - name: Add IKE crypto config to the firewall
    panos_ike_crypto_profile:
      provider: '{{ provider }}'
      state: 'present'
      name: 'vpn-0cc61dd8c06f95cfd-0'
      dh_group: ['group2']
      authentication: ['sha1']
      encryption: ['aes-128-cbc']
      lifetime_seconds: '28800'

  - name: Add IKE gateway config to the firewall
    panos_ike_gateway:
      provider: '{{ provider }}'
      state: 'present'
      name: 'IKEGW-Ansible'
      version: 'ikev2'
      interface: 'ethernet1/1'
      enable_passive_mode: True
      enable_liveness_check: True
      liveness_check_interval: '5'
      peer_ip_value: '1.2.3.4'
      pre_shared_key: 'CHANGEME'
      ikev2_crypto_profile: 'default'
      commit: False
  
  - name: create tunnel.1
    panos_tunnel:
      provider: '{{ provider }}'
      if_name: "tunnel.2"
      ip: ["10.1.1.1/32"]

  - name: Add IPSec tunnel to IKE gateway profile
    panos_ipsec_tunnel:
      provider: '{{ provider }}'
      name: 'IPSecTunnel-Ansible'
      tunnel_interface: 'tunnel.2'
      ak_ike_gateway: 'IKEGW-Ansible'
      ak_ipsec_crypto_profile: 'default'

...