---
# Ansible Playbook for Palo Alto Firewall 
# In this playbook it is going to connect to the hosts under heading "palo" in inventory file
# It will then configure an Admin user "george" with password "secret123@"
# It uses the Firewall API key to connect to the Firewall

- name: Create new admin user
  hosts: palo
  gather_facts: false
  connection: local

  collections:
    - paloaltonetworks.panos  

  vars:
    palo_provider:
      ip_address: '192.168.1.20'
      api_key: LUFRPT1Ud3hCS2plSlllTkZPUjZmYlRNc21RWlVZa2M9cytDZ2NqQVZKSEF4UU5Td09jcU1LemRyckovSHhxNVR5cTBUMnFIVGpkNjFHM3RUVDQ5SHVMVm9ZNUtFWVNYOQ==
  
  tasks:
    - name: configure george administrator
      panos_administrator:
        provider: '{{ provider }}'
        admin_username: 'george'
        admin_password: 'secret123@'
        superuser: true
        commit: true

...