## PLAYBOOK
# Playbook to configure BGP conditional advertisement forwarding
## DESCRIPTION
# Example playbook that will connect to the firewall using credentials provided saved in host var file 
## REQUIREMENTS
# pip install ansible
# ansible-galaxy install PaloAltoNetworks.paloaltonetworks
## EXECUTE
# ansible-playbook palo-bgp-conditional-advertisement.yaml
---
- name: Configure BGP Conditional Advertisement Rule
  hosts: PA-FW-01
  connection: local
  gather_facts: False

  collections:
    - paloaltonetworks.panos

  tasks:
    - name: Create BGP Non-Exist Filter for Conditional Advertisement
      panos_bgp_policy_filter:
        provider: '{{ provider }}'
        state: return-object
        vr_name: default
        name: ne-filter-01
        policy_name: cond-rule-01
        policy_type: conditional-advertisement
        filter_type: non-exist
        enable: true
        address_prefix:
          - name: 10.0.0.0/24
      register: non_exist

    - name: Create BGP Advertise Filter for Conditional Advertisement
      panos_bgp_policy_filter:
        provider: '{{ provider }}'
        state: return-object
        vr_name: default
        name: ad-filter-01
        policy_name: cond-rule-01
        policy_type: conditional-advertisement
        filter_type: advertise
        enable: true
        address_prefix:
          - name: 10.0.1.0/24
      register: advertise

    - name: Create BGP Conditional Advertisement Rule
      panos_bgp_conditional_advertisement:
        provider: '{{ provider }}'
        vr_name: default
        name: cond-rule-01
        enable: true
        non_exist_filter: '{{ non_exist.panos_obj }}'
        advertise_filter: '{{ advertise.panos_obj }}'
# Add the non_exist_filter and advertise_filter details to host_vars file

    - name: Update BGP Conditional Advertisement Rule
      panos_bgp_conditional_advertisement:
        provider: '{{ provider }}'
        vr_name: default
        name: cond-rule-01
        enable: false

    - name: Remove BGP Conditional Advertisement Rule
      panos_bgp_conditional_advertisement:
        provider: '{{ provider }}'
        state: absent
        vr_name: default
        name: cond-rule-01
        commit: true
...

