# DESCRIPTION
# Playbook that will configure basic networking. In particular this script will create layer configures BGP on Palo FW
#
# REQUIREMENTS
# pip install ansible
# ansible-galaxy install PaloAltoNetworks.paloaltonetworks
#
# EXECUTE
# ansible-playbook palo-add-bgp.yaml
---
- name: Apply basic BGP configuration to Palo FW
  hosts: PA-VM-02
  connection: local
  collections:
    - paloaltonetworks.panos

  tasks: 
  - name: Configure and enable BGP
    panos_bgp:
      provider: '{{ provider }}'
      vr_name: '{{ vr_name }}'
      router_id: '192.168.1.11'
      local_as: '64512'
      aggregate_med: yes
      always_compare_med: yes
      allow_redist_default_route: no
      enable: yes
      commit: yes