## PLAYBOOK
# Playbook to update a BGP aggregated rule
## DESCRIPTION
# Example playbook that will connect to the firewall using credentials provided saved in either host.yaml or vars.yaml files
# add vr_name in host var file or group_vars file
## REQUIREMENTS
# pip install ansible
# ansible-galaxy install PaloAltoNetworks.paloaltonetworks
## EXECUTE
# ansible-playbook palo-bgp-disable-aggrule.yaml
---
- name: Configure Aggregation Rules
  hosts: PA-VM-02
  connection: local
  gather_facts: False

  collections:
    - paloaltonetworks.panos
  
  tasks:
  - name: Disable BGP Aggregation Rule
    panos_bgp_aggregate:
      provider: '{{ provider }}'
      vr_name: '{{ vr_name }}'
      name: aggr-rule-01
      prefix: 10.0.0.0/24
      enable: false
      summary: true
      attr_med: 10
      attr_as_path_type: prepend
      attr_as_path_prepend_times: 1
      commit: true
...