# Ansible Playbook to import Configruation for Palo Alto Firewall
# Uses SSH to connect to the Firewall and config_file saved in same directory
---   
- name: import config
  hosts: PA-FW-01
  gather_facts: false
  connection: local
  collections:
    - paloaltonetworks.panos

  vars:
    cfg_file: candidate-template-empty.xml

  tasks:
  - name: wait for SSH (timeout 10min)
      wait_for: port=22 host='{{ provider.ip_address }}' search_regex=SSH timeout=600

  - name: checking if device ready
      panos_check:
        provider: '{{ provider }}'
      register: result
      until: not result|failed
      retries: 10
      delay: 10

  - name: import configuration
      panos_import:
        provider: '{{ provider }}'
        file: '{{cfg_file}}'
        category: 'configuration'
      register: result

  - name: load configuration
      panos_loadcfg:
        provider: '{{ provider }}'
        file: '{{result.filename}}'
        commit: False

  - name: set admin password
      panos_administrator:
        provider: '{{ provider }}'
        superuser: True
        commit: False

  - name: commit (blocks until finished)
      panos_commit:
        provider: '{{ provider }}'
...