## PLAYBOOK
# Playbook to add address groups to the Firewall
## DESCRIPTION
# Example playbook that will connect to the firewall using credentials provided saved in either host.yaml or vars.yaml files
## REQUIREMENTS
# pip install ansible
# ansible-galaxy install PaloAltoNetworks.paloaltonetworks
## EXECUTE
# ansible-playbook palo-FW-address-group.yaml

---
- name: Add some address groups to the firewall
  hosts: PA-FW-01
  connection: local
  gather_facts: False

  collections:
    - paloaltonetworks.panos

  tasks:
  - name: Create static address group
    panos_address_group:
      provider: '{{ provider }}'
      name: 'Prod-Instances'
      static_value: ['Test-1.1.1.1', 'Test-2.2.2.2', 'Test-3.3.3.3']
      tag: ['Prod']

  - name: Create dynamic address group
    panos_address_group:
      provider: '{{ provider }}'
      name: 'SI-Web-EPG'
      dynamic_value: 'SI-Web-EPG'
      tag: ['SI']

  - name: Delete address group
    panos_address_group:
      provider: '{{ provider }}'
      name: 'Old-Prod-Instances'
      state: 'absent'
      commit: true
...