---
- name: Delete Object Group
  hosts: palo
  gather_facts: false
  connection: local

  collections:
    - paloaltonetworks.panos  

- name: Delete object 'Test-Two'
  panos_address_object:
    provider: '{{ provider }}'
    name: 'Test-Two'
    state: 'absent'