## PLAYBOOK
# Playbook to create static routes on the Firewall
## DESCRIPTION
# Example playbook that will connect to the firewall using credentials provided saved in host var file 
## REQUIREMENTS
# pip install ansible
# ansible-galaxy install PaloAltoNetworks.paloaltonetworks
## EXECUTE
# ansible-playbook palo-add-static-routes.yaml
---
- name: Add Static Routes to the firewall
  hosts: PA-VM-PRI
  connection: local
  gather_facts: False

  collections:
    - paloaltonetworks.panos

  tasks:
  - name: Create first static route 'test-route1'
    panos_static_route:
      provider: '{{ provider }}'
      name: 'test-route1'
      destination: '11.11.11.0/24'
      nexthop: '180.10.10.100'
      virtual_router: "LAB-VR-RTR-1"

  - name: Create second static route 'test-route2'
    panos_static_route:
      provider: '{{ provider }}'
      name: 'test-route2'
      destination: '12.12.12.0/24'
      nexthop: '180.10.10.100'
      virtual_router: "LAB-VR-RTR-1"

  - name: Create third static route 'test-route3'
    panos_static_route:
      provider: '{{ provider }}'
      name: 'Test-Three'
      destination: '13.13.13.0/24'
      nexthop: '180.10.10.100'
      virtual_router: "LAB-VR-RTR-1"

  - name: Create fourth static route 'test-route4'
    panos_static_route:
      provider: '{{ provider }}'
      name: 'Test-Four'
      destination: '14.14.14.0/24'
      nexthop: '180.10.10.100'
      virtual_router: "LAB-VR-RTR-1"

  - name: Create fifth static route 'test-route5'
    panos_static_route:
      provider: '{{ provider }}'
      name: 'Test-Five'
      destination: '15.15.15.0/24'
      nexthop: '180.10.10.100'
      virtual_router: "LAB-VR-RTR-1"

  - name: Commit the changes to the Firewall
    panos_commit_firewall:
      provider: '{{ provider }}'
      description: 'adding new statice routes'
...
