# DESCRIPTION
# Playbook that will configure basic networking. In particular this script will:
# - create layer 3 trust and untrust zones
# - configure eth1/2 with DHCP and add it to untrust zone
# - configure eth1/4 with DHCP and add it to trust zone
# - set primary DNS server to Google's 8.8.8.8
# - set NTP servers to 0.uk.pool.ntp.org and 1.uk.pool.ntp.org
#
# REQUIREMENTS
# pip install ansible
# ansible-galaxy install PaloAltoNetworks.paloaltonetworks
#
# EXECUTE
# ansible-playbook palo-basic-net-config.yaml
---
- name: Apply basic network configuration to Palo FW
  hosts: PA-VM-02
  connection: local
  collections:
    - paloaltonetworks.panos

  tasks: 
      
    - name: configure ethernet1/1
      panos_interface:
        provider: '{{ provider }}'
        if_name: "ethernet1/1"
        mode: "layer3"
        ip: ["10.2.0.11/24"]
        enable_dhcp: false
        zone_name: "Inside"
        vr_name: "LAB-VIR-RTR-1"
        management_profile: "LAB-MGMT-PROFILE"
        create_default_route: "no"

    - name: configure ethernet1/2
      panos_interface:
        provider: '{{ provider }}'
        if_name: "ethernet1/3"
        mode: "layer3"
        ip: ["210.1.1.1/24"]
        enable_dhcp: false
        zone_name: "DMZ"
        vr_name: "LAB-VIR-RTR-1"
        management_profile: "LAB-MGMT-PROFILE"
        create_default_route: "no"
     
    - name: configure ethernet1/4
      panos_interface:
        provider: '{{ provider }}'
        if_name: "ethernet1/3"
        mode: "layer3"
        enable_dhcp: false
        ip: ["172.16.2.11/24"]
        zone_name: "DMZ"
        vr_name: "LAB-VIR-RTR-1"
        management_profile: "LAB-MGMT-PROFILE"
        create_default_route: "no"

    - name: set DNS, NTP and a login banner
      panos_mgtconfig:
        provider: '{{ provider }}'
        dns_server_primary: "8.8.8.8"
        ntp_server_primary: "0.uk.pool.ntp.org"
        ntp_server_secondary: "1.uk.pool.ntp.org"
        timezone: "Europe/London"
        login_banner: "Lab environment, do not enter unless authorised"
        commit: yes
...
