## PLAYBOOK
# Playbook to gather IP facts from the Firewall
## DESCRIPTION
# Example playbook that will connect to the firewall using credentials provided saved in host var file 
## REQUIREMENTS
# pip install ansible
# ansible-galaxy install PaloAltoNetworks.paloaltonetworks
## EXECUTE
# ansible-playbook palo-gather-tagipfacts.yaml
---
- name: Gather IP facts about a specific tag Firewall
  hosts: PA-FW-01
  connection: local
  gather_facts: False

  collections:
    - paloaltonetworks.panos

  tasks:
  - name: Get facts for specific tag
    panos_registered_ip_facts:
      provider: '{{ provider }}'
      tags: ['external']
    register: external_facts_registered_ip_facts
...
