# Ansible playbook for Palo Alto Firewall to create a source and destination nat rule and disable a security rule

---
- name: Create NAT SSH rule for 10.0.1.101
  hosts: palo
  gather_facts: false
  connection: local

  collections:
    - paloaltonetworks.panos

  tasks:
  - name: Create NAT SSH rule for 10.0.1.101
    panos_nat_rule:
      provider: '{{ provider }}'
      rule_name: "Web SSH"
      source_zone: ["Outside"]
      destination_zone: "Outside"
      source_ip: ["any"]
      destination_ip: ["10.0.0.100"]
      service: "service-tcp-221"
      snat_type: "dynamic-ip-and-port"
      snat_interface: "ethernet1/3"
      dnat_address: "10.0.1.101"
      dnat_port: "22"

  - name: disable a specific security rule
    panos_nat_rule:
      provider: '{{ provider }}'
      rule_name: 'Prod-Legacy 1'
      state: 'disable'
  